export interface DbPlayer {
  id: number;
  uid: string;
  name: string;
  posx: number;
  posy: number;
  posz: number;
  rotx: number;
  roty: number;
  rotz: number;
  rotw: number;
  platform: string | number;
  permissiongroup: string;
  health: number;
  hunger: number;
  thirst: number;
  brokenbones: number;
  temperature: number;
  dead: number;
  flying: number;
  clothes?: string;
  primaryspawn?: { x: number; y: number; z: number };
  secondaryspawn?: { x: number; y: number; z: number };
  tertiaryspawn?: { x: number; y: number; z: number };
  lastspawn: number;
  lastusedmount: number;
  lastusedvehicle: number;
  playtime: number;
  firstseen: number;
  lastseen: number;
}
